### PR TITLE
Add two perl web service scripts

### PR DESCRIPTION
**Pull request by philernst**
Add simple example (read pages within directory) and complex example (update all pages within directory)

### CODE REVIEW

**Comment by bradical** [comment]
Thanks! Would you mind renaming your `example` directory to something more specific like `page-read` or something?

**Comment by philernst** [comment]
You bet. I'm happy to do so.

**Comment by bradical** [comment]
... and finally delete the `example` directory :-). Sorry, I think when you moved it, Git didn't remove the old one. It usually do a `git mv` to make sure git properly tracks the move.

**Comment by bradical** [comment]
Thanks so much!

**Comment by bradical** [comment]
Whoops. One more thing: it looks like you have duplicates of that page read example now: `page-read` and `read-page`.

**Comment by philernst** [comment]
Oops. You're right. My git noobness is showing. I think it's all set now.

**Comment by bradical** [comment]
All good. Thanks again for your contribution to our code examples!

**Pull request merged**
