### PR TITLE
script to delete/unpublish by date comparison

### PR DESCRIPTION
**Pull request by ericepps**
(hope I did it right this time...)

### CODE REVIEW

**Comment by bradical** [comment]
Thanks @ericepps! The Pull Request looks good. Is the workflow just necessary to delete/un-publish in one step?

**Comment by ericepps** [comment]
Yes, that's the way I've done it, I guess because I had the workflows
already created. It'd probably be better to do that directly through a WS
call though?

**Comment by bradical** [comment]
Yea, I was thinking about doing it through web services. I know that the
web services "delete" operation doesn't have support for delete and
unpublish at this point. And I'm wondering if Cascade will allow you to
un-publish an asset in one web services call and immediately delete it in a
subsequent call. Definitely worth testing. Your solution is a good one
though if that doesn't work.

**Comment by ericepps** [comment]
Unless there's a way to wait until the publish job is complete, I don't 
think that will be possible. I get "The asset could not be deleted 
because it is currently being published." (I'm still on 7.0.7).

Eric

**Comment by bradical** [comment]
Thanks for confirming. Mind adding a quick note to line 6 of the README explaining that?

**Comment by bradical** [comment]
Also, your pull request looks good this time! (saw your note in the description) Generally, you want to create a "topic branch" in your project that roughly describes what your changes are (e.g. "delete-unpublish-old-content-example"). This makes it easier to maintain your local repository as well because once this gets merged in you can just fetch the latest from our repo and merge that to your "master" branch without issue. I've run into problems in the past with starting my pull request out of my own master branch and then trying to merge in those changes from the upstream repo when the pull request gets incorporated.

**Comment by bradical** [comment]
Great example. Thanks!

**Pull request merged**
